Algoritmo "circulo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 25/08/2021
Var

 r, a: real

Inicio

   escreva("Digite o raio do circulo: ")
   leia(r)

   a <- Pi * Exp(r, 2)
   
   escreva("A area do circulo é: ",a)
Fimalgoritmo